# Generated by Django 5.1 on 2024-08-31 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesearch', '0003_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviesearch.movie'),
        ),
    ]
